### ISSUE TITLE
Action controller error for downloading pdfs

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#414]
Currently there is a pdftk error when trying to download a pdf, any pdf.

On districthousing.org:

![screen shot 2017-10-02 at 8 20 26 pm](https://user-images.githubusercontent.com/578345/31105106-9c03c51e-a7af-11e7-9c88-f0085193a959.png)

In a local Docker setup of the app, `rake pull_pdfs` (the command which should sych pdfs) fails:

```
rake aborted!
cannot load such file -- bundler/setup
/Users/kev/dev/districthousing/config/boot.rb:6:in `<top (required)>'
/Users/kev/dev/districthousing/config/application.rb:1:in `<top (required)>'
/Users/kev/dev/districthousing/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

Not sure if that's an issue with the app itself or the Dockerization. 

Something is broken in pdf synching, from Google Drive where the master pdf files are stored to the application. We need a solution that fixes this and eliminates the need for manual intervention. We should also make sure this won't happen when Bread ultimately deploys the final app in their environment.

**Comment by kevko** [comment]
Welllll GitHub permission are annoying, so instead of being able to edit a mistake here, I'm just going to close this out and open a new issue.
